# Dont forget implement env.SLACK_API_TOKEN env.SLACK_CHANNEL_ID
# We can send to a channel, a thread, update a message in channel but can not do it in thread.
name: 'GHA slack notification'
description: 'Notify about workflow state in channel or thread'
inputs:
  status:  # id of input
    description: 'Current workflow status'
    required: true
  text:  # id of input
    description: 'Text to display in message'
    required: true
  color: 
    description: 'Color for attachment'
    required: false
    default: ""
  channel_id:
    description: 'Target channel id'
    required: false
    default: ""
  thread_ts:
    description: 'Target thread ts(id)'
    required: false
    default: ""
  message_ts:
    description: 'Target message ts(id)'
    required: false
    default: ""
outputs:
  message_ts:
    description: "message_ts for future update or usage for thread creation"
    value: ${{ fromJson(steps.send-message.outputs.slack-result).response.message.ts }}
runs:
  using: "composite"
  steps:
    - id: send-message
      uses: archive/github-actions-slack@v2.6.0
      with:
        slack-bot-user-oauth-access-token: ${{ env.SLACK_API_TOKEN }}
        slack-channel: ${{ inputs.channel_id || env.SLACK_CHANNEL_ID }}
        slack-text: " "
        slack-message-timestamp: ${{ inputs.message_ts }}
        slack-optional-thread_ts: ${{ inputs.thread_ts }}
        slack-blocks: >-
          [
              {
                "block_id": "text1",
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Building repo *product-service*"
                }
              },
              {
                "type": "divider"
              },
              {
                "block_id": "text2",
                "type": "context",
                "elements": [
                  {
                    "type": "image",
                    "image_url": "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Flag_of_Sweden.svg/1200px-Flag_of_Sweden.svg.png",
                    "alt_text": "images"
                  },
                  {
                    "type": "plain_text",
                    "text": "Estimated time: 1 min"
                  }
                ]
              },
              {
                "type": "divider"
              }
          ]
