# Dont forget implement env.SLACK_API_TOKEN env.SLACK_CHANNEL_ID
# We can send to a channel, a thread, update a message in channel but can not do it in thread.
name: 'GHA slack notification'
description: 'Notify about workflow state in channel or thread'
inputs:
  status:  # id of input
    description: 'Current action status'
    required: true
  text:  # id of input
    description: 'Text to display in message'
    required: true
runs:
  using: "composite"
  steps:
    - id: send-message
      uses: archive/github-actions-slack@v2.6.0
      with:
        slack-bot-user-oauth-access-token: ${{ env.SLACK_API_TOKEN }}
        slack-channel: ${{ env.SLACK_CHANNEL_ID }}
        slack-blocks: |
          [
            {
              "type": "header",
              "text": {
                "type": "plain_text",
                "text": "${{ github.workflow }}: ${{ github.job }}",
                "emoji": true
              }
            },
            {
              "type": "section",
              "fields": [
                {
                  "type": "mrkdwn",
                  "text": "*\n${{ inputs.status }}*"
                }
              ]
            },
            {
              "type": "section",
              "fields": [
                {
                  "type": "mrkdwn",
                  "text": "*Branch:*\n<https://github.com/${{ github.repository }}/${{ github.sha }} | ${{ github.ref }}>"
                },
                {
                  "type": "mrkdwn",
                  "text": "*SHA:*\n<https://github.com/${{ github.repository }}/commit/${{ github.sha }} | ${{ github.sha }}>"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Event:*\n${{ github.event_name }}"
                }
              ]
            },
            {
              "type": "context",
              "elements": [
                {
                  "type": "image",
                  "image_url": "https://github.githubassets.com/favicon.ico",
                  "alt_text": "github"
                },
                {
                  "type": "mrkdwn",
                  "text": "<https://github.com/${{ github.repository }} | ${{ github.repository }}>"
                },
                {
                  "type": "mrkdwn",
                  "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} | Workflow Run>"
                }
              ]
            }
          ]
